[project]
name = "de-pyspark-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "ipykernel~=6.31.0",
    "polars>=1.36.1",
    "pyspark~=4.0.1",
]
